version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make conf="" full
  build-check:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make conf="--check" full
  build-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make conf="--test" full
  build-clean:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make conf="--clean" full
workflows:
  version: 2
  level_builds:
    jobs:
      - build
      - build-check
      - build-test
      - build-clean

